# Generated by Django 5.1.5 on 2026-01-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scheduling", "📅 Better Scheduling"),
                            ("payments", "💰 Flexible Payments"),
                            ("messaging", "💬 In-App Messaging"),
                            ("digital", "📦 Digital Products"),
                            ("reports", "📊 Financial Reports"),
                            ("mobile", "📱 Mobile App"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
            ],
        ),
    ]
