# Generated by Django 5.1.5 on 2026-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_emaillead_city_emaillead_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillead",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="emaillead",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
